version: '2'
# Beets Music Organizer

services:
  beets:

    #image: linuxserver/beets
    build: .
    container_name: beets
    privileged: true
    restart: always
    ports:
      - 8337:8337

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /nas:/nas

    environment:
      - TZ=UTC
      - PGID=0
      - PUID=0

    # See: https://docs.docker.com/engine/reference/run/#cpu-share-constraint
    cpu_shares: 512
