version: '3'
# Docker Lidarr Music Downloader Compose File

services:
  lidarr:

    image: linuxserver/lidarr
    container_name: lidarr
    privileged: true
    restart: always
    ports:
      - 8686:8686

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker-lidarr/config:/config

      # Configure any other volmes/shares you want to map in...
      - /nas:/nas

    environment:
      - TZ=UTC
      - PGID=0
      - PUID=0

    healthcheck:
      test: curl --fail -s http://localhost:8686/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3