version: '3'

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    privileged: true

    ports:
      - 9117:9117

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker-jackett/config:/config

     # Configure to point to your mapped "blackhole" directory
      - /nzbget-downloads/jackett-blackhole:/downloads

    healthcheck:
      test: curl --fail -s http://localhost:9117/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3